name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark
            output/snake.gif?color_snake=#4CAF50&color_dots=#1a1a1a,#333333,#4d4d4d,#666666,#808080

      - name: Push to Repository
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update contribution snake'
          add: |
            output/snake.svg
            output/snake-dark.svg
            output/snake.gif